# C:\Users\User\OneDrive\Desktop\Buisness\KHM Smart Build\Projects\Training data\Sparky  training folder libraries
# __init__.py

from excel_gpt_update import analyze_text
from excel_gpt_update import check_info
from function_explanations import generate_function_explanations
from function_explanations import store_function_explanations
from main_train import main
from agents.Template_scripts.app import is_valid_int
from agents.Template_scripts.app import get_command
from agents.Template_scripts.app import map_command_synonyms
from agents.Template_scripts.app import execute_command
from agents.Template_scripts.app import get_text_summary
from agents.Template_scripts.app import get_hyperlinks
from agents.Template_scripts.app import shutdown
from agents.Template_scripts.app import start_agent
from agents.Template_scripts.app import message_agent
from agents.Template_scripts.app import list_agents
from agents.Template_scripts.app import delete_agent
from agents.Template_scripts.args import parse_arguments
from agents.Template_scripts.audio_text import read_audio_from_file
from agents.Template_scripts.audio_text import read_audio
from agents.Template_scripts.chat import create_chat_message
from agents.Template_scripts.chat import generate_context
from agents.Template_scripts.chat import chat_with_ai
from agents.Template_scripts.data_ingestion import configure_logging
from agents.Template_scripts.data_ingestion import ingest_directory
from agents.Template_scripts.data_ingestion import main
from agents.Template_scripts.evaluate_code import evaluate_code
from agents.Template_scripts.execute_code import execute_python_file
from agents.Template_scripts.execute_code import execute_shell
from agents.Template_scripts.execute_code import we_are_running_in_a_docker_container
from agents.Template_scripts.file_operations import check_duplicate_operation
from agents.Template_scripts.file_operations import log_operation
from agents.Template_scripts.file_operations import split_file
from agents.Template_scripts.file_operations import read_file
from agents.Template_scripts.file_operations import ingest_file
from agents.Template_scripts.file_operations import write_to_file
from agents.Template_scripts.file_operations import append_to_file
from agents.Template_scripts.file_operations import delete_file
from agents.Template_scripts.file_operations import search_files
from agents.Template_scripts.google_search import google_search
from agents.Template_scripts.google_search import google_official_search
from agents.Template_scripts.image_gen import generate_image
from agents.Template_scripts.image_gen import generate_image_with_hf
from agents.Template_scripts.image_gen import generate_image_with_dalle
from agents.Template_scripts.improve_code import improve_code
from agents.Template_scripts.llm_utils import call_ai_function
from agents.Template_scripts.llm_utils import create_chat_completion
from agents.Template_scripts.llm_utils import create_embedding_with_ada
from agents.Template_scripts.logs import Logger
from agents.Template_scripts.logs import TypingConsoleHandler
from agents.Template_scripts.logs import ConsoleHandler
from agents.Template_scripts.logs import AutoGptFormatter
from agents.Template_scripts.logs import remove_color_codes
from agents.Template_scripts.logs import print_assistant_thoughts
from agents.Template_scripts.machine_learning import ConstructionMLModel
from agents.Template_scripts.natural_language_generator import NaturalLanguageGenerator
from agents.Template_scripts.prompt import get_prompt
from agents.Template_scripts.prompt import construct_prompt
from agents.Template_scripts.question_answerer import QuestionAnswerer
from agents.Template_scripts.setup import prompt_user
from agents.Template_scripts.spinner import Spinner
from agents.Template_scripts.text_processor import TextProcessor
from agents.Template_scripts.times import get_datetime
from agents.Template_scripts.token_counter import count_message_tokens
from agents.Template_scripts.token_counter import count_string_tokens
from agents.Template_scripts.utils import clean_input
from agents.Template_scripts.utils import validate_yaml_file
from agents.Template_scripts.web_playwright import scrape_text
from agents.Template_scripts.web_playwright import scrape_links
from agents.Template_scripts.web_requests import is_valid_url
from agents.Template_scripts.web_requests import sanitize_url
from agents.Template_scripts.web_requests import check_local_file_access
from agents.Template_scripts.web_requests import get_response
from agents.Template_scripts.web_requests import scrape_text
from agents.Template_scripts.web_requests import scrape_links
from agents.Template_scripts.web_requests import create_message
from agents.Template_scripts.web_selenium import browse_website
from agents.Template_scripts.web_selenium import scrape_text_with_selenium
from agents.Template_scripts.web_selenium import scrape_links_with_selenium
from agents.Template_scripts.web_selenium import close_browser
from agents.Template_scripts.web_selenium import add_header
from agents.Template_scripts.workspace import path_in_workspace
from agents.Template_scripts.workspace import safe_path_join
#from agents.Template_scripts.template config.ai_config import AIConfig
#from agents.Template_scripts.template config.config import Config
#from agents.Template_scripts.template config.config import check_openai_api_key
#from agents.Template_scripts.template config.singleton import Singleton
#from agents.Template_scripts.template config.singleton import AbstractSingleton
#from agents.Template_scripts.template processing.html import extract_hyperlinks
#from agents.Template_scripts.template processing.html import format_hyperlinks
#from agents.Template_scripts.template processing.text import split_text
#from agents.Template_scripts.template processing.text import summarize_text
#from agents.Template_scripts.template processing.text import scroll_to_percentage
#from agents.Template_scripts.template processing.text import create_message
from data.raw_data.raw_text_prep import setup_logging
from data.raw_data.raw_text_prep import clean_and_tokenize
from data.raw_data.raw_text_prep import remove_punctuation
from data.raw_data.raw_text_prep import tokenize
from data.raw_data.raw_text_prep import remove_stop_words
from data.raw_data.raw_text_prep import lemmatize
from data.raw_data.raw_text_prep import process_text
from data.raw_data.raw_text_prep import main
from data.raw_data.tools.data_scraper import extract_data_from_thread
from data.raw_data.tools.Img_descr_pdfplumb import process_pdf_file
from data.raw_data.tools.PdfPlumb import process_pdf_file
from data.raw_data.tools.PdFPlumb_all import create_database_schema
from data.raw_data.tools.PdFPlumb_all import process_pdf_file
from data.raw_data.tools.pdf_reader import PDFReader
from data.raw_data.tools.Pdf_reader_ui import PDFReaderUI
from data.raw_data.tools.Scrape_two import extract_data_from_thread
#from data.raw_data.tools.web-crawlQA import TextParser
from data.raw_data.tools.database.ElectricicalKnowledge import create_connection
from data.raw_data.tools.database.ElectricicalKnowledge import create_table
from data.raw_data.tools.database.ElectricicalKnowledge import insert_electrical_knowledge
from data.raw_data.tools.database.ElectricicalKnowledge import get_electrical_knowledge_by_category
from data.raw_data.tools.database.ElectricicalKnowledge import update_electrical_knowledge
from data.raw_data.tools.database.ElectricicalKnowledge import main
#from data.raw_data.tools.text-prep.append_to_csv import append_data_to_csv
#from data.raw_data.tools.text-prep.Audio_Trans_clean import transcribe_audio_file
#from data.raw_data.tools.text-prep.Audio_Trans_clean import clean_transcript
#from data.raw_data.tools.text-prep.Audio_Trans_clean import convert_to_json
#from data.raw_data.tools.text-prep.create_embeddings import EmbeddingGenerator
#from data.raw_data.tools.text-prep.OPai_Sql_Q_electrical import create_quote
#from data.raw_data.tools.text-prep.OPai_Sql_Q_electrical import update_quote
#from data.raw_data.tools.text-prep.OPai_Sql_Q_electrical import get_quote
#from data.raw_data.tools.text-prep.OPai_Sql_Q_electrical import search_electrical_knowledge
#from data.raw_data.tools.text-prep.process_text_with_openai import generate_text
#from data.raw_data.tools.text-prep.YT_aud_CL_PR import YouTubeAudioProcessor
from data.structured_data.Preproces_Knowldge_base import extract_key_information
from gui.Sparky_gui import SparkyGUI
from gui.google_bard.sparky_bard import create_llm
from gui.hf_tools.agents.Agents import generate_response
from gui.hf_tools.agents.Agents import main
from gui.hf_tools.agents.prepare_data import split_data
from gui.hf_tools.agents.prepare_data import save_to_file
from gui.hf_tools.agents.prepare_data import main
from gui.hf_tools.agents.question_makergpt2 import generate_text
from gui.hf_tools.agents.question_makergpt2 import process_input_file
from gui.hf_tools.agents.question_makergpt2 import split_text
from gui.hf_tools.agents.question_makergpt2 import get_response
from gui.hf_tools.agents.TaskManager import Task
from gui.hf_tools.agents.TaskManager import TaskManager
from gui.hf_tools.agents.training_data_maker import generate_text
from gui.hf_tools.agents.training_data_maker import split_text
from gui.hf_tools.agents.training_data_maker import main
from gui.Sparky.admin_folders_dialog import AdminFoldersDialog
from gui.Sparky.ai_task_management import AITaskManagement
from gui.Sparky.data_cleaning_process import CleaningFunctionWidget
from gui.Sparky.data_cleaning_process import DataCleaningWindow
from gui.Sparky.generate_spreadsheet import read_workspace_file
from gui.Sparky.generate_spreadsheet import generate_project_info
from gui.Sparky.generate_spreadsheet import split_text
from gui.Sparky.generate_spreadsheet import create_spreadsheet
from gui.Sparky.GPT_convo_sorter import generate_response
from gui.Sparky.GPT_convo_sorter import get_additional_categories
from gui.Sparky.GPT_convo_sorter import generate_example_sentences
from gui.Sparky.image_create import ImageGenerator
from gui.Sparky.project_folders_dialog import ProjectFoldersDialog
from gui.Sparky.quote_tasks_dialog import QuoteTasksDialog
from gui.Sparky.schedule_tasks_dialog import ScheduleTasksDialog
from gui.Sparky.sparky_assistant_gpt4 import SparkyAssistantGPT4
from gui.Sparky.sparky_chat import SparkyChat
from gui.Sparky.Sparky_commands import fill_out_form
from gui.Sparky.Sparky_commands import apply_quotes
from gui.Sparky.Sparky_commands import apply_invoices
from gui.Sparky.Sparky_commands import apply_payments
from gui.Sparky.Sparky_commands import apply_inventory
from gui.Sparky.Sparky_commands import apply_customers
from gui.Sparky.Sparky_commands import apply_suppliers
from gui.Sparky.Sparky_commands import apply_projects
from gui.Sparky.Sparky_commands import apply_clients
from gui.Sparky.Sparky_commands import append_quotes
from gui.Sparky.Sparky_commands import append_invoices
from gui.Sparky.Sparky_commands import create_database
from gui.Sparky.Sparky_commands import drop_database
from gui.Sparky.Sparky_commands import update_database
from gui.Sparky.Sparky_commands import delete_database
from gui.Sparky.Sparky_commands import write_summary
from gui.Sparky.Sparky_commands import write_conversation
from gui.Sparky.Sparky_commands import search_devices
from gui.Sparky.Sparky_commands import add_device
from gui.Sparky.Sparky_commands import update_device
from gui.Sparky.Sparky_commands import delete_device
from gui.Sparky.Sparky_commands import fault_finder
from gui.Sparky.Sparky_commands import add_fault
from gui.Sparky.Sparky_commands import update_fault
from gui.Sparky.Sparky_commands import delete_fault
from gui.Sparky.sparky_features import Sparky_quoting
from gui.Sparky.sparky_features import InventoryControl
from gui.Sparky.sparky_features import Payroll
from gui.Sparky.sparky_features import JobScheduling
from gui.Sparky.sparky_features import CustomerCare
from gui.Sparky.sparky_features import IoTConnection
from gui.Sparky.sparky_features import disconnect_device
from gui.Sparky.sparky_features import ElectricalTheory
from gui.Sparky.sparky_gpt4_UI import process_image
from gui.Sparky.sparky_gpt4_UI import sparky_assistant
from gui.Sparky.sparky_gpt4_UI import main
from gui.Sparky.sparky_gpt4_UI import open_data_cleaning_gui
from gui.Sparky.sparky_gpt4_UI import show_schedule_tasks_dialog
from gui.Sparky.sparky_gpt4_UI import show_project_folders_dialog
from gui.Sparky.sparky_gpt4_UI import show_quote_tasks_dialog
from gui.Sparky.sparky_gpt4_UI import connect_to_iot_device
from gui.Sparky.Sparky_image_editor import ImageEditor
from gui.Sparky.Sparky_image_editor import main
from gui.Sparky.sparky_personality_description import SparkyPersonalityDescription
from gui.Sparky.tooltip_tab_widget import TooltipTabWidget
from gui.Sparky.tooltip_tab_widget import TooltipTabBar
from gui.Sparky.train_sparky import greet
from gui.Sparky.train_sparky import device_connected
from gui.Sparky.train_sparky import hobby_hint
from gui.Sparky.train_sparky import tell_joke
from gui.Sparky.train_sparky import explain_implications
from gui.Sparky.train_sparky import get_sparky_personality
from gui.Sparky.whisper_tools import AudioTranscription
from gui.Sparky.whisper_tools import TrainingDataGenerator
from gui.Sparky.whisper_tools import RealTimeTranscription
from gui.Sparky.whisper_tools import RecordAudio
from gui.Sparky.settings.commands.create_new_script import create_new_script
from gui.Sparky.settings.commands.create_new_script import ClassName
from gui.Sparky.settings.commands.functions_lib import get_function_description
from gui.Sparky.settings.commands.gpt4_functions_template import ClassName
from gui.Sparky.settings.commands.InventoryControlCommands import InventoryControl
from gui.Sparky.settings.commands.PayrollCommands import Payroll
from gui.Sparky.settings.commands.QuotingCommands import Quoting
from gui.Sparky.settings.commands.QuotingCommands import create_quote
from gui.Sparky.settings.commands.QuotingCommands import update_quote
from gui.Sparky.settings.commands.QuotingCommands import get_quote
from gui.Sparky.settings.features.InventoryControl import InventoryControl
from gui.Sparky.settings.features.Payroll import Payroll
from gui.Sparky.settings.features.Quoting import Quoting
from gui.Sparky.test.unit_test_AITaskManagement import TestAITaskManagement
from gui.utils.chatbot import generate_response
from gui.utils.connect_to_IoT_device import IotDeviceWindow
from gui.utils.data_loader import BS7671DataLoader
from gui.utils.FileCategorizerAI import Agent1
from gui.utils.FileCategorizerAI import Agent2
from gui.utils.FileCategorizerAI import Agent3
from gui.utils.FileCategorizerAI import SafetyTwin
from gui.utils.FileCategorizerAI import FileCategorizationGUI
from gui.utils.Init_library_GR import generate_imports
from gui.utils.insert_electrical_knowledge import insert_data
from gui.utils.interactive_formatter import create_connection
from gui.utils.interactive_formatter import get_random_question
from gui.utils.interactive_formatter import display_question
from gui.utils.interactive_formatter import prompt_user_answer
from gui.utils.interactive_formatter import compare_user_answer
from gui.utils.interactive_formatter import provide_feedback
from gui.utils.interactive_formatter import main
from gui.utils.knowledge_base import create_connection
from gui.utils.knowledge_base import create_table
from gui.utils.knowledge_base import main
from gui.utils.response_formatter import format_openai_response
from gui.utils.response_formatter import format_definition
from gui.utils.response_formatter import format_example
from gui.utils.response_formatter import format_image
from gui.utils.response_formatter import format_paragraph
from gui.utils.response_formatter import format_question
from gui.utils.response_formatter import format_answer
from gui.utils.response_formatter import format_section
from gui.utils.response_formatter import format_chapter
from gui.utils.response_formatter import get_database_connection
from gui.utils.response_formatter import get_random_question
from gui.utils.response_formatter import get_section
from gui.utils.response_formatter import get_definitions
from gui.utils.response_formatter import format_electrical_knowledge
from gui.utils.response_formatter import format_recommended_reading
from gui.utils.response_formatter import format_webpage_summary
from gui.utils.response_formatter import format_joke
from gui.utils.ui_classes import QuestionLabel
from gui.utils.ui_classes import ReferenceLabel
from gui.utils.database.history import check_if_table_exists
from gui.utils.database.history import create_connection
from gui.utils.database.history import create_conversation_history_table
from gui.utils.database.history import insert_conversation_log
from gui.utils.database.history import get_conversation_history
from gui.utils.database.history import load_conversation_history
from gui.utils.database.history import save_conversation_history
from gui.utils.database.history import save_conversation_log
from gui.utils.database.history import delete_conversation_log
from gui.utils.database.history import delete_all_conversation_logs
from gui.utils.Prep.ConversationLoader import ConversationLoader
from gui.utils.Prep.doodle_sketch_pad import DoodleSketchPad
from gui.utils.Prep.file_conversion import text_to_speech
from gui.utils.Prep.file_conversion import speech_to_text
from gui.utils.Prep.file_conversion import audio_to_text
from gui.utils.Prep.file_conversion import video_to_text
from gui.utils.Prep.file_conversion import pdf_to_text
from gui.utils.Prep.file_conversion import image_to_text
from gui.utils.Prep.file_conversion import convert_file
from gui.utils.Prep.file_management import FileManager
from gui.utils.Prep.file_organizer import FileOrganizer
from gui.utils.Prep.file_organizer import DataConverter
from gui.utils.Prep.file_organizer import DataPreprocessor
from gui.utils.Prep.media_tab import MediaTab
from gui.utils.Prep.preprocessing import remove_punctuation
from gui.utils.Prep.preprocessing import remove_numbers
from gui.utils.Prep.preprocessing import to_lower
from gui.utils.Prep.preprocessing import preprocess_text
from gui.utils.Prep.preprocessing import preprocess_data
from gui.utils.Prep.save_data import save_data
from gui.utils.Prep.VideoRecorder import VideoRecorder
from gui.utils.Prep.video_processor import VideoProcessor
from gui.utils.Prep.video_processor import VideoProcessorGUI
from gui.utils.Prep.you_tube.transcribe_video import transcribe_video
from Libraries.Librarys import DataLibrary
from Libraries.Librarys import ModelsLibrary
from Libraries.Librarys import EvaluationLibrary
from Libraries.Librarys import UtilsLibrary
from scripts.completions import generate_completions
from scripts.gui import MainWindow
from scripts.twitter import send_tweet
from scripts.updated_full_tree import list_files
from scripts.updated_full_tree import get_functions
from scripts.updated_full_tree import analyze_text
from scripts.updated_full_tree import check_info
from scripts.watch_responses import FileChangeHandler
