# c:\Users\User\OneDrive\Desktop\Buisness\KHM Smart Build\Projects\Training data\Sparky  training\gui\utils folder libraries
# __init__.py

from .chatbot import generate_response
from .connect_to_IoT_device import IotDeviceWindow
from .data_loader import BS7671DataLoader
from .FileCategorizerAI import Agent1
from .FileCategorizerAI import Agent2
from .FileCategorizerAI import Agent3
from .FileCategorizerAI import SafetyTwin
from .FileCategorizerAI import FileCategorizationGUI
from .Init_library_GR import generate_imports
from .insert_electrical_knowledge import insert_data
from .interactive_formatter import create_connection
from .interactive_formatter import get_random_question
from .interactive_formatter import display_question
from .interactive_formatter import prompt_user_answer
from .interactive_formatter import compare_user_answer
from .interactive_formatter import provide_feedback
from .interactive_formatter import main
from .knowledge_base import create_connection
from .knowledge_base import create_table
from .knowledge_base import main
from .response_formatter import format_openai_response
from .response_formatter import format_definition
from .response_formatter import format_example
from .response_formatter import format_image
from .response_formatter import format_paragraph
from .response_formatter import format_question
from .response_formatter import format_answer
from .response_formatter import format_section
from .response_formatter import format_chapter
from .response_formatter import get_database_connection
from .response_formatter import get_random_question
from .response_formatter import get_section
from .response_formatter import get_definitions
from .response_formatter import format_electrical_knowledge
from .response_formatter import format_recommended_reading
from .response_formatter import format_webpage_summary
from .response_formatter import format_joke
from .ui_classes import QuestionLabel
from .ui_classes import ReferenceLabel
from database.history import check_if_table_exists
from database.history import create_connection
from database.history import create_conversation_history_table
from database.history import insert_conversation_log
from database.history import get_conversation_history
from database.history import load_conversation_history
from database.history import save_conversation_history
from database.history import save_conversation_log
from database.history import delete_conversation_log
from database.history import delete_all_conversation_logs
from Prep.ConversationLoader import ConversationLoader
from Prep.doodle_sketch_pad import DoodleSketchPad
from Prep.file_conversion import text_to_speech
from Prep.file_conversion import speech_to_text
from Prep.file_conversion import audio_to_text
from Prep.file_conversion import video_to_text
from Prep.file_conversion import pdf_to_text
from Prep.file_conversion import image_to_text
from Prep.file_conversion import convert_file
from Prep.file_management import FileManager
from Prep.file_organizer import FileOrganizer
from Prep.file_organizer import DataConverter
from Prep.file_organizer import DataPreprocessor
from Prep.media_tab import MediaTab
from Prep.preprocessing import remove_punctuation
from Prep.preprocessing import remove_numbers
from Prep.preprocessing import to_lower
from Prep.preprocessing import preprocess_text
from Prep.preprocessing import preprocess_data
from Prep.save_data import save_data
from Prep.VideoRecorder import VideoRecorder
from Prep.video_processor import VideoProcessor
from Prep.video_processor import VideoProcessorGUI
from Prep.you_tube.transcribe_video import transcribe_video
